# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6424c7389684a92e9305a8c901eb2bd82ab7cebb48821a8755e6d40dea639893cd1f8d54d3546c8338e9c9eb5395cc3059103b2e5e308476fce30db7b5f7eebd

test:
  secret_key_base: 8f348acddc8185225e7c9983491d03b5876e92f2dae41b64961d99453995c1481e8efd0b43f047854e8dd9b1aa99df650e6b8dd817535d6f3a0ef71bf6dbe749

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
